B.pyを作りました #1
morita-rui/gitremote2 pull request #6
Opened 2024-10-31 03:32 UTC by Morijyobi-guchi

レビューをお願いします。
close #1

2024-10-31 03:40 UTC, reiya0517 requested changes

2024-10-31 03:40 UTC, reiya0517 commented on B.py
> +   print("こんにちは")
ハローちがう

2024-10-31 03:40 UTC, reiya0517 commented on B.py
> +   print("こんにちは")
```suggestion
   むむむ
```

2024-10-31 03:41 UTC, morita-rui requested changes
しっかりーーー

2024-10-31 03:41 UTC, morita-rui commented on B.py
> +def hallo():
```suggestion
def hello():
```
こうでしょ！

2024-11-01 02:24 UTC, morita-rui approved these changes
ok

2024-11-01 02:24 UTC, reiya0517 approved these changes
天才だね

2024-11-01 02:26 UTC, merged